### ISSUE TITLE
ubuntu usage

### ISSUE THREAD

**Issue by mehranexpert** [Varbaek/xsser#1]
How install all dependency on ubuntu 16.04 ?

**Comment by Varbaek** [comment]
In Ubuntu Desktop 16.04.1 LTS (https://www.ubuntu.com/download/desktop), with a clean install, after apt-get clean && apt-get upgrade has been run:
1. Check that Python 2.7.* is in use with "python -V". In my case, Python 2.7.12 is returned. 
2. Check that "git" has been installed. If you can't run the git command, then you need to: sudo apt-get install git
3. Once you have git installed, which you can verify by running the git command, or "git --version", which in my case returns 2.7.4, you can proceed to the next step.
4. Run: git clone https://github.com/Varbaek/xsser and wait for it to finish.
5. Run: cd xsser/
6. Run: python xsser.py
7. If you get an error such as "ImportError: No module named pygame", then execute the following command: sudo apt-get install python-pygame 

The other dependencies:
* Gnome aka gnome-terminal (already installed)
* Bash (already installed)
* Msfconsole (NOT INSTALLED BY DEFAULT!)
* Netcat aka nc (already installed)
* cURL aka curl (already installed)
* PyGame (NOT INSTALLED BY DEFAULT! Refer to: sudo apt-get install python-pygame)

In order to install Msfconsole, aka The Metasploit Framework console, you will need to either install the framework manually via github:
https://github.com/rapid7/metasploit-framework and https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment
Or by using their installers from: 
https://www.rapid7.com/products/metasploit/download/community/

Using the installers, is the preferred approach as they ship with all the dependencies you need as well. 

Installation and basic usage of Metasploit is outside of the scope, of this comment/tutorial, but use the links above for installation. For usage, please refer to:
https://www.offensive-security.com/metasploit-unleashed/ 
http://resources.metasploit.com/
https://github.com/rapid7/metasploit-framework/wiki
